name: livestock_repository

version: 1.0.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  pedantic: ^1.8.0
  equatable: ^0.6.0
  rxdart: ^0.22.4

  # Add Firebase plugins
  firebase_core: ^0.4.0+9
  cloud_firestore: ^0.12.9+5
  firebase_auth: ^0.15.1