name: livestock_repository

version: 1.0.0

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  pedantic: ^1.8.0
  equatable: ^1.1.1

  # Add Firebase plugins
  firebase_core: ^0.4.4
  cloud_firestore: ^0.13.5
  firebase_auth: ^0.16.0